### ISSUE TITLE
gtk3 set_resizable does not work 

### ISSUE THREAD

**Issue by ghost** [ruby-gnome2/ruby-gnome2#856] opened 2016-08-12 15:42 UTC

**Comment by cedlemo** [comment] 2016-08-17 12:05
It would be great if you provided more informations or a simple working script that show the problem.

here is a simple example that show that `Gtk::Window#resizable` works.

```ruby
require "gtk3"

window = Gtk::Window.new

window.title = "Test resizable"
window.set_default_size(200, 200)
toggle_button = Gtk::Button.new(:label => "toggle resizable")

# By default Gtk::Window are resizable

toggle_button.signal_connect "clicked" do |button|
  if window.resizable?
    window.resizable = false
    button.label = "Not resizable"
  else
    window.resizable = true
    button.label = "Resizable"
  end
end
window.add(toggle_button)

window.signal_connect "destroy" do
  Gtk.main_quit
end

window.show_all

Gtk.main
```

@kou,

I think that you can close this issue.

**Comment by kou** [comment] 2016-08-17 12:09
I close this.
This issue should not be reopened until a script that reproduces the problem is provided.

**Closed by kou** 2016-08-17 12:09 UTC
