### ISSUE TITLE
undefined method `parse' for class `#<Class:Gdk::Color>' 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [ruby-gnome2/ruby-gnome2#1037] opened 2017-06-09 21:28 UTC
Hey, i just wanted to give Ruby a try with Gtk3 to compare it to Python/Gtk

So i got the example for Gtk.Window object
```ruby
require "gtk3"

window = Gtk::Window.new("First example")
window.set_size_request(400, 400)
window.set_border_width(10)

button = Gtk::Button.new(:label => "Say hello")
button.signal_connect "clicked" do |_widget|
  puts "Hello World!!"
end

window.add(button)
window.signal_connect("delete-event") { |_widget| Gtk.main_quit }
window.show_all

Gtk.main

```
But whenever i run the code using `ruby window.rb`  I get this error : 
```bash
/usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:20:in `alias_method': undefined method `parse' for class `#<Class:Gdk::Color>' (NameError)
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:20:in `singleton class'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:19:in `<class:Color>'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:18:in `<module:Gdk>'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:125:in `require_post_libraries'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:61:in `post_load'
	from /usr/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.6/lib/gobject-introspection/loader.rb:45:in `load'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:20:in `load'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3.rb:57:in `init'
	from /usr/lib/ruby/gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb:64:in `init'
	from /usr/lib/ruby/gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb:40:in `const_missing'

```

Libraries versions:
```
Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
ruby-gtk3: 3.1.6
Gtk: 3.22.15
```
System information:
```
Archlinux 
Gnome Shell : 3.25.2
```

**Comment by cedlemo** [comment] 2017-06-10 10:44
Hi, your code run fine on my system which is ArchLinux too but I use the gems from the git repository.
How did you install the gems ? (`pacman|yaourt` or `gem`).

**Comment by bil-elmoussaoui** [comment] 2017-06-10 10:49
I used the quarry repository (which contains a lot of gem's). And i'm using the testing version of gnome.

**Comment by cedlemo** [comment] 2017-06-10 16:17
Could you do : 

```
irb -r gtk3
irb(main):001:0> Gtk::Version
=> Gtk::Version::STRING
=> "3.22.15"
```

It is to see if Ruby-Gtk3 use the good gtk3 version.

**Comment by bil-elmoussaoui** [comment] 2017-06-10 16:23
I'm getting the same error :/ 
Here's the output on my terminal
![screenshot from 2017-06-10 18-23-19](https://user-images.githubusercontent.com/7660997/27004474-ed84893c-4e09-11e7-8a67-839a92742649.png)

**Comment by cedlemo** [comment] 2017-06-10 16:38
The 2 differences between your system and mine are : 
*  you installed the gems via *quarry*
*  you installed the dev version of gnome.

In order to test if you problem come from the gems of *quarry* : 

Could you try to uninstall your ruby gems and install the gtk3 gems via this command:

```
gem install --user-install gtk3
```

This will install the gems in your home directory (`~/.gems/) and test.

After that we will try to see if the problem is related to the presence of the dev version of Gnome (Does it come with dev version of Gtk 3 ?)

**Comment by bil-elmoussaoui** [comment] 2017-06-10 21:19
I still have the same problem after removing the gem installed using `quarry` and reinstalling it using `gem`. Anyway, i will see if downgrading to the stable version fixes the issue or not

**Comment by bil-elmoussaoui** [comment] 2017-06-22 16:48
I've tried to downgrade to stable version but nothing was fixed here :(

**Comment by cedlemo** [comment] 2017-06-23 17:59
Could you do this in order to see if it will fix you issue : 
* first find the installed file **gdk3/lib/gdk3/color.rb**
  * /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb or
  * ~/.gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/color.rb for example

find the line 20 with : 

    alias_method :parse_raw, :parse

and edit it with : 

    alias_method :parse_raw, :parse if respond_to? :parse


It looks like you Gtk3 does not have the gdk_color_parse function.

**Comment by bil-elmoussaoui** [comment] 2017-06-23 18:04
Thanks ! Now i'm getting this 
```bash
irb(main):001:0> Gtk::Version::STRING
NameError: uninitialized constant Gdk::WindowAttributesType
Did you mean?  Gdk::WindowRedirect
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:112:in `const_missing'
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:154:in `const_get'
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:154:in `block in resolve_constant_name'
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:140:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:140:in `inject'
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:140:in `resolve_constant_name'
	from /usr/lib/ruby/gems/2.4.0/gems/glib2-3.1.6/lib/glib2/deprecatable.rb:33:in `define_deprecated_enums'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/deprecated.rb:172:in `<class:Window>'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/deprecated.rb:166:in `<module:Gdk>'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/deprecated.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:136:in `require_post_libraries'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:61:in `post_load'
	from /usr/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.6/lib/gobject-introspection/loader.rb:45:in `load'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3/loader.rb:20:in `load'
	from /usr/lib/ruby/gems/2.4.0/gems/gdk3-3.1.6/lib/gdk3.rb:57:in `init'
	from /usr/lib/ruby/gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb:64:in `init'
	from /usr/lib/ruby/gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb:40:in `const_missing'
	from (irb):1
```

**Comment by cedlemo** [comment] 2017-06-23 18:06
Have you Gtk4 installed ? There is another user that has the same issue than you and uninstall Gtk4 fixed it.

**Comment by cedlemo** [comment] 2017-06-23 18:09
@kou, the Gtk4 libs can be installed on some system, we will have to prevent the Gtk3 GI loader to load the last version of the Gtk lib.

**Comment by bil-elmoussaoui** [comment] 2017-06-23 18:37
@cedlemo Yeah, removing gtk4 fixed the issue. But this shouldn't cause any issue? This is really annoying as if i create ruby & gtk3 application, i must ask every user to make sure they don't have gtk4 installed.;;

**Comment by cedlemo** [comment] 2017-06-23 18:48
> This is really annoying as if i create ruby & gtk3 application, i must ask every user to make sure they don't have gtk4 installed.;;

It will be fixed soon.

**Comment by cedlemo** [comment] 2017-06-23 19:01
@bil-elmoussaoui , while we are waiting for @kou answer, would you like to try to modify the gtk3.rb file like this  : 

```ruby
diff --git a/gtk3/lib/gtk3.rb b/gtk3/lib/gtk3.rb
index 014e2eb4a..ad693db96 100644
--- a/gtk3/lib/gtk3.rb
+++ b/gtk3/lib/gtk3.rb
@@ -62,7 +62,7 @@ module Gtk
       end
       Gio.init if Gio.respond_to?(:init)
       Gdk.init if Gdk.respond_to?(:init)
-      loader = Loader.new(self, argv)
+      loader = Loader.new(self, argv, :version => "3.0")
       loader.load("Gtk")
     end
   end
```

in you */usr/lib/ruby/gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb* or in *~/.gems/2.4.0/gems/gtk3-3.1.6/lib/gtk3.rb*. Using the version of Gtk should stop the loader to use the Gtk4 GObjectIntrospection files.

**Comment by kou** [comment] 2017-06-24 03:06
Use this patch!
https://github.com/ruby-gnome2/ruby-gnome2/commit/e5f1b96a7235358c7bf2cd3bda5c1dcc56d9a05a.patch

**Comment by kou** [comment] 2017-07-10 14:30
gtk3 gem 3.1.7 includes the fix.

**Closed by kou** 2017-07-10 14:30 UTC
