### ISSUE TITLE
Issues with glib 2.44.0 on MAC OSX

### ISSUE THREAD

**Issue by jwaldrip** [ruby-gnome2/ruby-gnome2#369] opened 2015-04-06 19:32 UTC
The following error is occurring on OSX with glib2 and glib 2.44.0 installed on OSX.

```
$ gem install glib2
Building native extensions.  This could take a while...
ERROR:  Error installing glib2:
	ERROR: Failed to build gem native extension.

    /Users/jwaldrip/.rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150406-12564-6uluav.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for rb_define_alloc_func() in ruby.h... yes
checking for rb_block_proc() in ruby.h... yes
checking for new allocation framework... yes
checking for attribute assignment... no
checking for Windows... no
checking for gobject-2.0 version (>= 2.12.0)... yes
checking for gthread-2.0... yes
checking for unistd.h... yes
checking for io.h... no
checking for g_spawn_close_pid() in glib.h... yes
checking for g_thread_init() in glib.h... yes
checking for g_main_depth() in glib.h... yes
checking for g_listenv() in glib.h... yes
checking for rb_check_array_type() in ruby.h... yes
checking for rb_check_hash_type() in ruby.h... yes
checking for rb_exec_recursive() in ruby.h... yes
checking for rb_errinfo() in ruby.h... yes
checking for rb_sourcefile() in ruby.h... yes
checking for rb_sourceline() in ruby.h... yes
checking for ruby_set_current_source() in ruby.h... no
checking for rb_thread_call_without_gvl() in ruby.h... yes
checking for ruby_native_thread_p() in ruby.h... yes
checking for rb_thread_call_with_gvl() in ruby.h... yes
checking for rb_str_new_cstr() in ruby.h... yes
checking for rb_gc_register_mark_object() in ruby.h... yes
checking for rb_exc_new_str() in ruby.h... yes
checking for curr_thread in ruby.h,node.h... no
checking for rb_curr_thread in ruby.h,node.h... no
creating ruby-glib2.pc
creating glib-enum-types.c
creating glib-enum-types.h
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling glib-enum-types.c
glib-enum-types.c:1181:9: error: use of undeclared identifier 'G_WIN32_OS_ANY'
      { G_WIN32_OS_ANY, "G_WIN32_OS_ANY", "any" },
        ^
glib-enum-types.c:1182:9: error: use of undeclared identifier 'G_WIN32_OS_WORKSTATION'
      { G_WIN32_OS_WORKSTATION, "G_WIN32_OS_WORKSTATION", "workstation" },
        ^
glib-enum-types.c:1183:9: error: use of undeclared identifier 'G_WIN32_OS_SERVER'
      { G_WIN32_OS_SERVER, "G_WIN32_OS_SERVER", "server" },
        ^
3 errors generated.
make: *** [glib-enum-types.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/jwaldrip/.gem/ruby/2.2.1/gems/glib2-2.2.4 for inspection.
Results logged to /Users/jwaldrip/.gem/ruby/2.2.1/extensions/x86_64-darwin-14/2.2.0-static/glib2-2.2.4/gem_make.out
```

**Comment by tomchapin** [comment] 2015-04-06 19:36
:+1:

**Comment by mtasaka** [comment] 2015-04-06 21:23
This is a duplicate of #361

**Closed by mtasaka** 2015-04-06 21:23 UTC
